### ISSUE TITLE
DELETE on Invoice API failing

### ISSUE THREAD

**Issue by drowe** [square/square-ruby-sdk#120]
**Describe the bug**
A previously fixed issue where a DELETE API call on Invoices was passing an empty object (as opposed to nil) which the Square API server didn't like, and assumed it was a bad request. This was fixed by changing the default `parameters` variable to `nil` instead of `{}`. With the latest API (31.x, atleast - I've not kept up) - the change was reverted, but the parameters are not as clearly exposed due to the APIMatic changes.

**Expected behavior**
The body should be empty, if Square requires this, and the Invoice should be deleted.

**To Reproduce**
Steps to reproduce the bug:
1. Create Invoice (whether API or UI driven does not apply)
2. Attempt to delete Invoice using client.invoices.delete() passing the correct invoice_id.

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Square SDK version**
31.0.0.20230816

**Comment by zenmasterjobo** [comment]
hi @drowe as mentioned in the Square forum post, this issue has been fixed as part of the release for version 32. Feel free to reopen if the problem comes back up again!

**Comment by drowe** [comment]
Thank you! Linking to this commit as the core fix, upstream of this repo - https://github.com/apimatic/faraday-client-adapter/commit/28e4243b2e3de3a66725f4ec95397473512ed8fa
