### ISSUE TITLE
README.md is cut off in default display

### ISSUE THREAD

**Issue by jcrate** [square/square-ruby-sdk#2]
There must be a length limit on the README.md when it is automatically displayed at the root of the project.  The last data structure displayed is "Tender", and there are quite a few more data structures that should display after that. As a result, clicking on links like "#update-customer-request" doesn't do anything. 

If you click on the README.md file in the source listing, it loads the full page. 

Perhaps a better solution would be to have a short readme with a link to a separate file with the documentation, so a user would not have broken links.

**Comment by shaofu88** [comment]
@jcrate, Thank you for bringing up this issue. We will investigate and find a fix for it. Thanks again.

**Comment by havenwood** [comment]
Fixed by 8a1efad26e7939900150c41ca3293b726e0d48a2.

Thanks for reporting this issue!
