### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by iax7** [square/square-ruby-sdk#29]
All requests and response documents are with wrong links.

![image](https://user-images.githubusercontent.com/6983510/71854708-ab9a3000-30a4-11ea-822a-46a4e3a87eac.png)

**Comment by havenwood** [comment]
Thank you for reporting the broken docs links! We'll investigate and fix.

**Comment by sseaman** [comment]
This has been addressed with the latest release.  If you see this anywhere else, please tell us!
