### ISSUE TITLE
Excessive Code Duplication

### ISSUE THREAD

**Issue by mvastola** [square/square-ruby-sdk#31]
So I have access to an alpha-stage square API which does not currently have an SDK available. As a result, I attempted to extend this gem for internal use to cover additional API endpoints/methods.

In reviewing the code present in the `lib/square/api` directory, I was unpleasantly surprised to find that every single function in this directory consists of 90+% duplicated code. This was frustrating and time-consuming for me to have to work with, and it must be even more frustrating and time-consuming for those who maintain it.

In approaching what I needed to code, I ended up piecing together this (albeit not yet tested/polished) straightforward ~50-line function that generates SDK methods dynamically (in true ruby fashion). If used everywhere possible, the `api` subdirectory -- not including comments -- which currently is 4,387 lines of code can (quite realistically) be reduced to < 500 lines of code.

No pressure to actually use this code, but please do consider a major refactoring effort because the code as it is hurts to read.

```ruby
module Square
  # BaseApi.
  class BaseApi
    DEFAULT_HEADERS = { 'accept' => 'application/json' }
    class << self
      def configure_endpoint(name, http_method, path, *optional_parameter_names, request_body: nil, extra_headers: {})
        name = name.to_sym
        query_parameters.map!(&:to_sym)
        http_method = http_method.to_s.upcase.to_sym
        request_body = %i[POST PUT PATCH].include?(http_method) ? true : false if request_body.nil?
        _headers = DEFAULT_HEADERS.dup
        _headers['content-type'] = 'application/json; charset=utf-8' if request_body
        _headers.merge!(extra_headers)

        required_parameter_names = path.scan(/(?<={)\w+(?=})/).map(&:to_sym)
        required_parameter_names << :body if request_body
        allowed_parameter_names = required_parameter_names + optional_parameter_names

        define_method name do |**kwargs|
          missing_keywords = required_parameter_names - kwargs.keys
          unknown_keywords = kwargs.keys - allowed_parameter_names
          raise ArgumentError, "missing keyword: #{missing_keywords.first}" unless missing_keywords.empty?
          raise ArgumentError, "unknown keyword: #{unknown_keywords.first}" unless unknown_keywords.empty?

          # Prepare query url.
          _query_builder = config.get_base_uri
          _query_builder << path

          _template_parameter_names = required_parameter_names - %i[body]
          _template_parameters = kwargs.slice(*_template_parameter_names).stringify_keys
          _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, _query_parameters)

          _query_parameter_names = allowed_parameter_names - required_parameter_names
          _query_parameters = kwargs.slice(*_query_parameter_names).stringify_keys
          _query_builder = APIHelper.append_url_with_query_parameters(_query_builder, _query_parameters)

          _query_url = APIHelper.clean_url _query_builder

          # Prepare and execute HttpRequest.
          _request_parameters = { headers: _headers }
          _request_parameters[:parameters] = kwargs[:body].to_json if request_body
          _request = config.http_client.send(http_method, **_request_parameters)
          OAuth2.apply(config, _request)
          _response = execute_request(_request)

          # Return appropriate response type.
          decoded = APIHelper.json_deserialize(_response.raw_body)
          _errors = APIHelper.map_response(decoded, ['errors'])
          ApiResponse.new(_response, data: decoded, errors: _errors)
        end
      end
    end

    # Insert existing BaseApi code here
  end
end
```

To use: 
```ruby
module Square
  # CustomersApi
  class CustomersApi < BaseApi
    configure_endpoint :list_customers,        :GET,     '/v2/customers', :cursor, :sort_field, :sort_order
    configure_endpoint :create_customer,       :POST,    '/v2/customers'
    configure_endpoint :search_customers,      :POST,    '/v2/customers/search'
    configure_endpoint :retrieve_customer,     :GET,     '/v2/customers/{customer_id}'
    configure_endpoint :update_customer,       :PUT,     '/v2/customers/{customer_id}'
    configure_endpoint :delete_customer,       :DELETE,  '/v2/customers/{customer_id}'
    configure_endpoint :create_customer_card,  :POST,    '/v2/customers/{customer_id}/cards'
    configure_endpoint :delete_customer_card,  :DELETE,  '/v2/customers/{customer_id}/cards/{card_id}'
  end
end
```

**Comment by StephenJosey** [comment]
Hey @mvastola thanks for the feedback. Just FYI our SDKs are generated automatically and therefore not idiomatic, which is why you're seeing this. I've shared this with the team, though.

**Comment by mvastola** [comment]
@StephenJosey, ok, but even if a script is used, that script can be changed to make much less repetitive code. As it is now, it's much harder to alter and add features.

Even more importantly though, this implies it's impossible to make PRs against this repo that could be integrated.  The code used to generate this library also needs to be open sourced so that this becomes possible.

**Comment by StephenJosey** [comment]
We definitely appreciate the feedback, and we're looking into how we can clean this up. However, just for clarification, we will not be open-sourcing the code generator.

**Comment by havenwood** [comment]
@mvastola PRs are welcome, but it's best to open an issue ticket first to discuss since we'll need to update the generator to match merged PR. As the generated code becomes more idiomatic and less repetitive, PRs should be easier to make and merge. Thank you for the feedback!

**Comment by mvastola** [comment]
> We definitely appreciate the feedback, and we're looking into how we can clean this up. However, just for clarification, we will not be open-sourcing the code generator.

@StephenJosey, this feels a bit weird to me. This brings into question why this repo is even on GitHub if it's not truly open source. I mean I guess there can be bugs, but by posting things on GitHub, companies send the message they embrace open source. 

This isn't really a fair deal though -- people (Square's customers) can use this repo to improve your product (because you're willing to take their changes and apply them to your generator), but they then don't benefit from being able to reuse the codebase they're ultimately contributing to. Even worse, this is being done somewhat covertly -- you do not make the fact that this code is machine-generated public knowledge, so people don't know the terms of engagement when they contribute.

It really prompts the question -- why even have this on GitHub if this SDK isn't a truly collaborative effort? Why not just publish direct to rubygems? This isn't really how open source is supposed to work..
