### ISSUE TITLE
Client.new uninitiated constant

### ISSUE THREAD

**Issue by daBee** [square/square-ruby-sdk#46]
`Ryby 2.7.0`
Having issues with `Client.new`: 

    client = Square::Client.new(environment: 'sandbox', access_token: $sandbox_access_token)
    ==> uninitialized constant Square::Client (NameError)

The `gem` is indeed loaded, but can't get past this for some reason.  

Tried this as well:

    require 'square'
    client = Square::Client.new(access_token: $sandbox_access_token)
    ==> uninitialized constant Square::Client (NameError)

Same error.  Not sure what to do.

**Comment by daBee** [comment]
Tried 3 different versions on my Mac workstation, same issue.  `CentOS 7` on `ruby 2.5.1`, same issue.

**Comment by StephenJosey** [comment]
Using macbook, testing with Ruby 2.7.0 and Ruby 2.4.2 and have not been able to replicate this error. It sounds like the gem is not being properly loaded since it's throwing that error. How does your `Gemfile` look?

**Comment by daBee** [comment]
Hi Stephen.  Just tried another box with the same output.  

    gem 'square'

But I do not have:

    gem 'square_connect'

Everything else is loading.  `square` installed properly, even manually using `gem install`.

**Comment by daBee** [comment]
**Solved.**  

gem 'square.rb'

...and not ...

gem 'square'

It's essential.  Should have chosen a different name for the `gem`, as file suffices are normally clipped.  As well, some uninstalling of `faraday`then `bundle` were needed.
