### ISSUE TITLE
Support faraday v1.x

### ISSUE THREAD

**Issue by syoder** [square/square-ruby-sdk#47]
Use of this gem in our Rails app is restricting our ability to update some other gems which now require `faraday` v1.0.x. In order to allow faraday v1.0.x, you would need to relax the dependency requirement for faraday, but also update `faraday_middleware` to v1.0.0

Any chance you would be willing to update those to? And/or would you be willing to accept a PR which makes those changes?

**Comment by jessdelacruzsantos** [comment]
@syoder  Thanks for bringing this to our attention. We're now working on this issue.

**Comment by syoder** [comment]
Awesome, thank you! I know `faraday` dependencies in general are a mess right since they bumped to v1.x back in January.

**Comment by sseaman** [comment]
This should be fixed in the latest release.
