### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by georgewambold** [square/square-ruby-sdk#62]
Working through the [Get an Instance of an API object and call its methods](https://github.com/square/square-ruby-sdk#get-an-instance-of-an-api-object-and-call-its-methods) section of the README, it seems following line is out of date:

```
# Call create_customer method to create a new customer in this Square account
result = client.customers.create_customer(request_body)
```

results in this error: 

``` 
missing keyword: :body (ArgumentError)
```

It runs fine when you add the `body:` keyword argument like this:

```
# Call create_customer method to create a new customer in this Square account
result = client.customers.create_customer(body: request_body)
```

Just thought I'd let you all know! Thanks for all the work on Square, I just started working with it but so far the documentation has been great 👏🏼

**Comment by StephenJosey** [comment]
Thanks for sharing this! I'll pass this along to see it gets updated :)

**Comment by hukid** [comment]
This is a documentation issue and we've fixed in the latest document refresh.
