### ISSUE TITLE
Update deprecated OAuth renew_token method

### ISSUE THREAD

**Issue by georgewambold** [square/square-ruby-sdk#67]
It looks like the [`o_auth.renew_token`](https://github.com/square/square-ruby-sdk/blob/master/doc/api/o-auth.md#renew-token) method/endpoint has been deprecated for a while now and token renewing is now done in a different way that's [documented in the OAuth documentation](https://developer.squareup.com/docs/oauth-api/cookbook/renew-oauth-tokens). 

Is the Square team planning on updating the SDK? This functionality is required for anyone using Square's OAuth, it would be really nice to have an updated SDK method for it.

**Comment by StephenJosey** [comment]
Can you clarify what you mean? The RenewToken endpoint is marked as deprecated in the docs (https://github.com/square/square-ruby-sdk/blob/master/doc/api/o-auth.md) for this SDK. Furthermore, it's not needed; you now use ObtainToken for refreshing tokens.

**Comment by georgewambold** [comment]
@StephenJosey Ahh you're right. That's my mistake. I thought you had deprecated the RenewToken endpoint without replacing it, I didn't realize that you could use ObtainToken for renewing tokens. 

Thanks for the prompt response 👍🏼
