### ISSUE TITLE
Support Faraday versions greater than 1.3.0

### ISSUE THREAD

**Issue by xxswingxx** [square/square-ruby-sdk#74]
Hi, I've tried to upgrade from `10.0.0.202104217` to `12.0.0.20210616` but it seems the new version is more restrictive with the faraday version. We're currently using 1.4.1 and the previous dependency used to be `~> 1.0, >= 1.0.1` but now the dependencies indicates `~> 1.0', '<= 1.3.0`. Why was it restricted this way?

**Comment by v-kumar** [comment]
This is the only gem blocking us from Rails 7 upgrade due to dependency on Faraday 1.0 + Faraday middleware 1.0. Any update on when you will support Faraday 2.0?

**Comment by v-kumar** [comment]
Any update on this @wolfadex , @hukid  ?

There's a PR #96 that fixes this issue awaiting your attention as well.

**Comment by wolfadex** [comment]
@v-kumar and @xxswingxx the release that went out yesterday, [19.0.0.20220420](https://rubygems.org/gems/square.rb), includes updated versions of Faraday (as well as additional features and dropping support for Ruby 2.5). I hope this helps both of you with your work. Please let us know if it is still holding you back, and if you have any API related questions I hop you'll reach out in our [Slack](https://buildwithsquare.slack.com/ssb/redirect) or [Forums](https://developer.squareup.com/forums/).
