### ISSUE TITLE
Support for Ruby 3.0

### ISSUE THREAD

**Issue by acallaghan** [square/square-ruby-sdk#86]
Hi there, the latest version of the `gemspec` doesn't cover Ruby 3.0, and prevents installation on Ruby 3.0. It previously allowed for installation, and so now I can't upgrade the SDK past version 13.1. 

I noticed that earlier released versions of the SDK allowed for Ruby 3.0, but then recently the gemspec was changed to exclude it - is there a reason for this change? https://github.com/square/square-ruby-sdk/commit/43ac3e0fed74cccc47487c80d520dfbbb80422d1#diff-5a67e013e1d330fd45ad26ebe314d631faec8eeaa96f9425b36f893afcde3af3R17

**Comment by acallaghan** [comment]
Is there any word on this?

**Comment by hukid** [comment]
@acallaghan We're looking into this right now.

**Comment by acallaghan** [comment]
@hukid Great, thank you!

**Comment by hukid** [comment]
@acallaghan we just released a fix to support `3.0` again, please use the latest version `16.0.1.20211117`. https://github.com/square/square-ruby-sdk/pull/89
